### ISSUE TITLE
Segfault when running release binary

### ISSUE THREAD

**Issue by israellevin** [the-drunk-coder/megra.rs#5]
I'm getting a segfault when I try to run the pre-built binaries.

```sh
$ wget -q https://github.com/the-drunk-coder/megra.rs/releases/download/v0.0.12/megra_rs_0_0_12_linux_ringbuffer.AppImage
$ chmod +x megra_rs_0_0_12_linux_ringbuffer.AppImage
$ ./megra_rs_0_0_12_linux_ringbuffer.AppImage
Segmentation fault
$ dmesg
[17664.559260] bin[107151]: segfault at 0 ip 0000000000000000 sp 00007ffd01c92d18 error 14 in bin[55a8d77cc000+114000] likely on CPU 1 (core 1, socket 0)
[17664.559270] Code: Unable to access opcode bytes at 0xffffffffffffffd6.
```

Looks like a really awesome project, thanks!

**Comment by the-drunk-coder** [comment]
Hi, which distro are you on? I'm building the AppImage on Arch, but I recently found out that that might not be the best Idea ...

**Comment by israellevin** [comment]
I'm using Debian. Not sure why the build process would be different for Arch.

**Comment by the-drunk-coder** [comment]
It's not the build process itself ...

Even though creating an AppImage SHOULD include everything necessary to run the application, the code is still compiled/linked against libraries that are available on the system you build it on, and if these are of a newer date than the one on the system you try to run it on, there might be version mismatches etc. 

It's usually less problematic in the other direction, building on a system with older libraries and run it on the newer system ...

**Comment by israellevin** [comment]
Thanks, now I get it. I always thought AppImages are statically linked, but that's just because I have zero experience with them :)

**Comment by the-drunk-coder** [comment]
Just released a new version and included 2 different AppImage builds, I hope there's one for everyone in there now :)

**Comment by israellevin** [comment]
Since I'm running debian, I tried `megra_rs_0_0_13_ubuntu_ringbuffer.AppImage`:
```sh
i@chakra:~$ ./megra_rs_0_0_13_ubuntu_ringbuffer.AppImage
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run.
You might still be able to extract the contents of this AppImage
if you run it with the --appimage-extract option.
See https://github.com/AppImage/AppImageKit/wiki/FUSE
for more information
```

I already had fuse3 installed, but once I installed the `libfuse2` package the error went away, only to be replaced with:
```sh
i@chakra:~$ ./megra_rs_0_0_13_ubuntu_ringbuffer.AppImage
invalid output mode, assume stereo
using a live buffer time of: 3
Failed to open client because of error: ClientError(FAILURE | SERVER_FAILED)
Failed to open client because of error: ClientError(FAILURE | SERVER_FAILED)
live buf time samples: 132300
real time stream pre-fill 137
real time stream pre-fill 137
[INPUT] error starting input!
[OUTPUT] error starting output!
base dir is: "/home/i/.config/megra"
no startup file found
load samples from path: "/home/i/.config/megra/samples"
a command (load default sample sets)
thread 'main' panicked at src/main.rs:808:10:
called `Result::unwrap()` on an `Err` value: WinitEventLoop(Os(OsError { line: 786, file: "/home/nik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/mod.rs", error: Misc("neither WAYLAND_DISPLAY nor WAYLAND_SOCKET nor DISPLAY is set.") }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Happily, `megra_rs_0_0_13_arch_ringbuffer.AppImage` was able to launch with no errors :partying_face:

I immediately noticed an improvement in the way keyboard input is handled (the old version, which I eventually managed to build and run, would capture keys that I use to for window management, so, for example, <super>+j, which I use for switching between windows, would also print the character `j` on the editor).

Awesome! Thanks!
